% !Rnw root = ../main.Rnw
<<setupseverity, cache=FALSE, echo=FALSE, include=FALSE, results='asis'>>=
opts_knit$set(self.contained=FALSE)
@

\chapter{Severity}
\label{sec:severity}

\section{Error, Testing, and Severity}
\label{sec:errortestingandseverity}

\section{Inferences About Discrepancies}
\label{sec:inferencesaboutdiscrepancies}

\section{Calculating Severity}
\label{sec:calculatingseverity}

